### ISSUE TITLE
Feature request: parse information required for verification

### ISSUE THREAD

**Issue by Jurajzovinec** [tamtamchik/app-store-receipt-parser#2]
### Why
With the deprecation of the`/verifyReceipt` endpoint, more projects will try to implement "in-device" verification on the server. For the [verification](https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device), more information is required to be obtained from the #PKCS7 container such as:
- receipt_creation_date
- bundle_id
- application_version
- hash
- in_app

BTW: awesome work @tamtamchik  👏🏼

**Comment by Jurajzovinec** [comment]
@tamtamchik Just want to share with you that the solution is no feature is no longer requested from my side. Managed to resolve using this [thread](https://stackoverflow.com/questions/77553782/how-to-decode-pkcs7-asn-1-using-javascript)

Feel free to close this issue

**Comment by tamtamchik** [comment]
@Jurajzovinec wow! Your solution is great! 👏 
Do you mind me partially porting it into this package someday?

**Comment by DePasqualeOrg** [comment]
@Jurajzovinec, I tried your solution on the receipt I received from Apple's endpoint (https://data-development.appattest.apple.com/v1/attestationData, https://data.appattest.apple.com/v1/attestationData), but it doesn't pass the schema validation. Any idea how to resolve this?

For context:
https://developer.apple.com/documentation/devicecheck/assessing_fraud_risk

When I run the following:

```typescript
const { result } = asn1js.fromBER(receiptBuffer);
console.log(result);
```

I get this:

```
Sequence {
  blockLength: 3774,
  error: '',
  warnings: [],
  valueBeforeDecodeView: Uint8Array(3774) [
    <values omitted>
  ],
  name: '',
  optional: false,
  idBlock: LocalIdentificationBlock {
    blockLength: 1,
    error: '',
    warnings: [],
    valueBeforeDecodeView: Uint8Array(0) [],
    isHexOnly: false,
    valueHexView: Uint8Array(0) [],
    tagClass: 1,
    tagNumber: 16,
    isConstructed: true
  },
  lenBlock: LocalLengthBlock {
    blockLength: 1,
    error: '',
    warnings: [],
    valueBeforeDecodeView: Uint8Array(0) [],
    isIndefiniteForm: true,
    longFormUsed: false,
    length: 0
  },
  valueBlock: LocalConstructedValueBlock {
    blockLength: 3772,
    error: '',
    warnings: [],
    valueBeforeDecodeView: Uint8Array(3772) [
      <values omitted>
    ],
    value: [ [ObjectIdentifier], [Constructed] ],
    isIndefiniteForm: true
  }
}
```

**Comment by Jurajzovinec** [comment]
@DePasqualeOrg I would recommend placing your receipt to https://lapo.it/asn1js/ and adjusting your schema definition according to it. 

EDIT: https://developer.apple.com/documentation/devicecheck/assessing_fraud_risk looking on this [link](https://developer.apple.com/documentation/devicecheck/assessing_fraud_risk) I guess you are trying this solution with a different type of receipt which has different structure resulting in the verification failure. You must define a new schema that fits your use case. 
If you have a problem with a schema definition you can paste "in-app purchase receipt" from [here](https://stackoverflow.com/questions/33843281/apple-receipt-data-sample/33961925#33961925) to https://lapo.it/asn1js  and compare generated schema with schema in this code example.

**Comment by Jurajzovinec** [comment]
@tamtamchik Sure go ahead!

**Comment by DePasqualeOrg** [comment]
> @DePasqualeOrg I would recommend placing your receipt to https://lapo.it/asn1js/ and adjusting your schema definition according to it.

Thanks! The structure is very long and complex. Do I have to replicate all of that in the schema? The schema in your example looks much shorter.

Alternatively, is there a way to parse these receipts without specifying the schema?
